name: storybook_example
description: A Flutter project with storybook.
publish_to: 'none'
version: 1.0.0+1
authors:
  - Alex Melnyk

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  storybook_flutter: ^0.5.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
